In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
csv = pd.read_csv('mower_market_snapshot.csv',delimiter=";")

In [4]:
csv.head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614

In [5]:
csv["prod_cost"]

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

In [6]:
csv[csv["prod_cost"].isin(["unknown"])]

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
100,28.029561,0.040033,18993,746.108663,350.216029,unknown,auto-portee,Hight,3anss,0.007847,0.802719
154,26.317938,0.098641,19642,272.038610,865.688164,unknown,electrique,Low,2_ans.,0.001632,0.425166
166,39.703060,0.073723,18870,248.010000,70.271198,unknown,electrique,Low,2 ans,0.002607,0.679325
479,36.259976,0.105738,18620,288.507312,74.897367,unknown,electrique,Low,2 ans.,0.001733,0.451514
532,40.218428,0.091096,18555,259.753146,848.659019,unknown,electrique,Low,2_ans.,0.002731,0.711726
569,44.771225,0.241101,18411,60.565166,367.821566,unknown,essence,Low,1an,0.001190,0.627962
923,67.500998,0.196182,19191,63.859993,885.550319,unknown,essence,Low,1 an.,0.001234,0.651009
981,64.607864,0.247584,18387,59.588596,878.615866,unknown,essence,Medium,1an.,0.001736,0.915787
983,52.234773,0.253485,18503,68.359089,392.653716,unknown,essence,Hight,1ans,0.000989,0.521938
1091,43.616434,0.202734,18651,60.221030,895.108605,unknown,essence,Low,1_an,0.001103,0.581745
1223,46.611471,0.239549,19160,59.147640,876.032341,unknown,essence,Low,1an.,0.001378,0.726867
1357,57.936910,0.232674,18329,59.878009,381.677052,unknown,essence,Low,1_ans,0.001188,0.626693
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622

In [12]:
csv.isnull().sum()

capacity           0
failure_rate       0
id                 0
margin             0
price              0
prod_cost         18
product_type       0
quality            0
warranty           0
market_share       0
attractiveness     0
dtype: int64

In [8]:
csv.groupby(["warranty"]).first()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,market_share,attractiveness
warranty,,,,,,,,,,
1 an,67.502725,0.214099,19615,62.182262,74.158501,11.976239018890924,essence,Medium,0.001328,0.700719
1 an.,65.652799,0.223053,18417,60.015189,70.983842,10.96865352892595,essence,Low,0.001410,0.743966
1 ans,78.038063,0.249144,18341,63.285773,73.686591,10.400818248587784,essence,Medium,0.001358,0.716233
1_an,52.924334,0.194703,18908,61.071253,71.257964,10.186711558764442,essence,Low,0.001287,0.678782
1_an.,43.829130,0.250942,19209,63.334842,73.591682,10.25683960401562,essence,Low,0.001019,0.537717
1_ans,69.184953,0.188034,18670,64.417542,76.273928,11.856385675229458,essence,Hight,0.001452,0.765866
1an,70.472944,0.215419,18671,65.848069,77.413521,11.565452175873386,essence,Medium,0.001193,0.629464
1an.,44.470418,0.201931,18828,62.065913,73.743963,11.678049782822576,essence,Low,0.001100,0.580604
1ans,0.056632,0.214791,19311,69.617555,82.215855,12.598300496114296,essence,Medium,0.000949,0.500491
2 ans,31.897593,0.092226,19620,263.227921,366.225489,102.99756784515532,electrique,Low,0.002938,0.765499
2 ans.,45.186621,0.099352,18392,279.423506,405.463775,126.04026925777649,electrique,Medium,0.002225,0.579652
2 anss,0.042489,0.094642,19550,252.743747,360.914396,108.17064902568966,electrique,Hight,0.003298,0.859263
2_ans,39.913900,0.072738,19315,245.389890,380.446873,135.05698252866299,electrique,Medium,0.002362,0.615381
2_ans.,32.943583,0.084185,19274,290.590317,376.585196,85.99487906022657,electrique,Medium,0.002476,0.645080
2_anss,28.078019,0.090630,19612,272.393102,360.710463,88.31736106911566,electrique,Low,0.002774,0.722786
2ans,28.572722,0.082485,19102,278.134706,393.710397,115.57569098132525,electrique,Medium,0.002276,0.592944
2ans.,38.415445,0.084900,19005,256.526597,373.053456,116.52685979197881,electrique,Low,0.002055,0.535390
2anss,36.916862,0.093666,18509,248.957677,365.740382,116.78270498219175,electrique,Low,0.002834,0.738396
3 ans,19.548213,0.035428,18268,728.284617,905.297503,177.01288573033196,auto-portee,Medium,0.007596,0.777051
3 ans.,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,0.006840,0.699792
3 anss,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,0.007925,0.810730
3_ans,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,0.006179,0.632129
3_ans.,12.242635,0.035492,18448,757.351286,930.615022,173.26373572791334,auto-portee,Hight,0.007488,0.766056
3_anss,14.028989,0.034757,19560,637.200636,785.615675,148.41503918168814,auto-portee,Low,0.007457,0.762884
3ans,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,0.006360,0.650648
3ans.,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,0.007406,0.757614
3anss,21.720148,0.035431,18495,679.310789,840.411156,161.1003672316781,auto-portee,Medium,0.007629,0.780437

In [9]:
csv["warranty"] = csv["warranty"].apply(lambda x: x[0])

In [10]:
csv.groupby(["warranty"]).first()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,market_share,attractiveness
warranty,,,,,,,,,,
1,67.502725,0.214099,19615,62.182262,74.158501,11.976239018890924,essence,Medium,0.001328,0.700719
2,31.897593,0.092226,19620,263.227921,366.225489,102.99756784515532,electrique,Low,0.002938,0.765499
3,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,0.006360,0.650648

In [21]:
csv.groupby(pd.cut(csv["price"], [0, 300,500,1000])).mean().loc[:,["capacity", "failure_rate", "margin","market_share", "attractiveness"]]

              capacity  failure_rate      margin  market_share  attractiveness
price
(0, 300]     56.933206      0.220407   67.479837      0.001225        0.626233
(300, 500]   38.632563      0.100551  263.736848      0.002431        0.632159
(500, 1000]  25.351682      0.069466  566.520813      0.005862        0.696661

In [23]:
csv["product_type"] = csv["product_type"].apply(lambda x: 1 if x=="essence" else 2 if x=="electrique" else 3)

In [25]:
csv.groupby(["product_type"]).first()

,capacity,failure_rate,id,margin,price,prod_cost,quality,warranty,market_share,attractiveness
product_type,,,,,,,,,,
1,67.502725,0.214099,19615,62.182262,74.158501,11.976239018890924,Medium,1,0.001328,0.700719
2,31.897593,0.092226,19620,263.227921,366.225489,102.99756784515532,Low,2,0.002938,0.765499
3,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,Low,3,0.006360,0.650648

In [30]:
csv = csv.assign(Essence=csv["product_type"].apply(lambda x: 1 if x==1else 0), Electrique=csv["product_type"].apply(lambda x: 1 if x==2 else 0), Auto_portee=csv["product_type"].apply(lambda x: 1 if x==3 else 0))
csv.groupby(["product_type"]).first()

,capacity,failure_rate,id,margin,price,prod_cost,quality,warranty,market_share,attractiveness,Essence,Electrique,Auto_portee
product_type,,,,,,,,,,,,,
1,67.502725,0.214099,19615,62.182262,74.158501,11.976239018890924,Medium,1,0.001328,0.700719,1,0,0
2,31.897593,0.092226,19620,263.227921,366.225489,102.99756784515532,Low,2,0.002938,0.765499,0,1,0
3,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,Low,3,0.006360,0.650648,0,0,1